[package]
name = "check_cpu_hyper-threading"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
simple-error = "0.2.3"
